resources:
  apps:
    sample_streamlit_app:
      name: sample-streamlit-app
      description: Sample Streamlit application
      source_code_path: ../src/app/ui

      command:
        - streamlit
        - run
        - app.py
