name: Trigger Databricks Job
on:
  push:
    branches: [feature/dg_code]
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Databricks CLI
        run: |
          pip install --upgrade databricks-cli
          
      - name: Run notebook
        env:
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
        run: |
          export DATABRICKS_HOST="${DATABRICKS_HOST}"
          export DATABRICKS_TOKEN="${DATABRICKS_CLIENT_ID}:${DATABRICKS_CLIENT_SECRET}"
          databricks jobs run-now --job-id ${{ vars.JOB_ID }}
